/* =========================================================================
   Club name pool for the football pyramid.
   -------------------------------------------------------------------------
   Eight divisions of 20 clubs = 160 persistent world slots once the first
   four Level 7 regional divisions are enabled. The user's club takes one of
   them, so 159+ AI names are required.

   Club identities deliberately evoke familiar English football geography and
   culture without copying official club branding, crests or exact identities.
========================================================================= */

export const CLUBS: string[] = [
  // Top-flight inspired identities
  "Manchester Devils",
  "Manchester Blue",
  "Liverpool Reds",
  "North London Cannons",
  "North London Lilywhites",
  "West London Blues",
  "Newcastle Black & White",
  "Birmingham Villans",
  "Brighton Seagulls",
  "West London Bees",
  "South London Eagles",
  "Fulham Whites",
  "Merseyside Blue",
  "Bournemouth Cherries",
  "Nottingham Reds",
  "Wolverhampton Gold",
  "East London Hammers",
  "Leicester Foxes",
  "Leeds Whites",
  "Southampton Saints",

  // Championship-inspired identities
  "Burnley Clarets",
  "Sheffield Blades",
  "Middlesbrough Reds",
  "Coventry Sky Blues",
  "Norwich Canaries",
  "Watford Hornets",
  "West Brom Stripes",
  "Bristol Robins",
  "Swansea Swans",
  "Cardiff Bluebirds",
  "Hull Tigers",
  "Stoke Potters",
  "Preston Whites",
  "Blackburn Blue & White",
  "Millwall Lions",
  "QPR Hoops",
  "Portsmouth Blues",
  "Derby Rams",
  "Oxford Yellows",
  "Plymouth Greens",

  // League One-inspired identities
  "Bolton Wanderers",
  "Barnsley Reds",
  "Reading Royals",
  "Wigan Latics",
  "Blackpool Tangerines",
  "Huddersfield Terriers",
  "Charlton Addicks",
  "Lincoln Imps",
  "Peterborough Posh",
  "Wycombe Blues",
  "Exeter Grecians",
  "Leyton Orient Reds",
  "Mansfield Stags",
  "Northampton Cobblers",
  "Rotherham Millers",
  "Stevenage Borough",
  "Shrewsbury Blues",
  "Burton Brewers",
  "Cambridge Amber",
  "Crawley Reds",

  // League Two-inspired identities
  "Bradford Bantams",
  "Doncaster Rovers",
  "Chesterfield Spires",
  "Fleetwood Cods",
  "Gillingham Gills",
  "Grimsby Mariners",
  "Harrogate Sulphurites",
  "MK White",
  "Newport Dragons",
  "Notts Black & White",
  "Salford Reds",
  "Swindon Robins",
  "Tranmere Rovers",
  "Walsall Saddlers",
  "Barrow Bluebirds",
  "Cheltenham Robins",
  "Colchester Blues",
  "Crewe Railwaymen",
  "Morecambe Shrimps",
  "Accrington Reds",

  // Level 7 regional expansion.
  "Banbury Cross",
  "Brackley Borough",
  "Kettering Athletic",
  "Stourbridge Town",
  "Redditch Borough",
  "Stratford Athletic",
  "Halesowen FC",
  "Bedford Borough",
  "Stamford Town",
  "Spalding Athletic",
  "Leamington Vale",
  "Nuneaton Borough",
  "Bromsgrove Athletic",
  "Coalville Town",
  "Harborough United",
  "Royston Borough",
  "Hitchin Athletic",
  "Barwell Town",
  "Alvechurch FC",
  "Needham Borough",

  "Salisbury Rovers",
  "Poole Athletic",
  "Dorchester Town",
  "Wimborne United",
  "Taunton Borough",
  "Tiverton Athletic",
  "Plymouth Parkway",
  "Gosport Town",
  "Havant Borough",
  "Walton Athletic",
  "Bracknell Town",
  "Chertsey Rovers",
  "Hungerford United",
  "Swindon Borough",
  "Gloucester Vale",
  "Basingstoke Town",
  "Sholing Athletic",
  "Winchester City",
  "Farnborough Rovers",
  "Weston Athletic",

  "Hornchurch Athletic",
  "Dulwich Borough",
  "Lewes Town",
  "Folkestone United",
  "Cray Wanderers",
  "Billericay Town",
  "Chatham Athletic",
  "Horsham Borough",
  "Carshalton United",
  "Hashtag Athletic",
  "Potters Bar Town",
  "Wingate Borough",
  "Canvey Athletic",
  "Whitehawk FC",
  "Bognor Regis Town",
  "Hendon Borough",
  "Cheshunt Athletic",
  "Dartford Rovers",
  "Ramsgate Town",
  "Burgess Hill Athletic",

  "Macclesfield Town",
  "Worksop Athletic",
  "Hyde United",
  "Morpeth Town",
  "Whitby Athletic",
  "Ashton Borough",
  "Guiseley Town",
  "Lancaster City",
  "Prescot Rovers",
  "Ilkeston Athletic",
  "Matlock Town",
  "Bamber Bridge FC",
  "Hebburn Athletic",
  "Mickleover Town",
  "Gainsborough Athletic",
  "Workington Borough",
  "Warrington Town",
  "Stockton Athletic",
  "Leek Town",
  "Basford United",
];
