/**
 * Presentation-only aliases for the fictional football world.
 *
 * Persisted club identities and save-sensitive source names must never change.
 * These aliases make the pyramid feel recognisably English while keeping the
 * canonical simulation keys untouched.
 */
const CLUB_PRESENTATION_ALIASES: Record<string, string> = {
  // 2026/27 Premier Division inspired set — 20 clubs.
  "Ashford City": "AFC Bournemuth",
  "Millbrook": "Arsenol",
  "Northfield": "Aston Viller",
  "Redwood FC": "Brentford City",
  "Kingsbridge": "Brighton & Hove Athletic",
  "Halewood United": "Chelsey",
  "Stanmoor": "Coventry Town",
  "Fairwind": "Crystal Palais",
  "Portlee": "Evertoon",
  "Blackrock Athletic": "Fulhem",
  "Silverdale": "Hull United",
  "Whitby Rangers": "Ipswich City",
  "Broadmarsh": "Leeds City",
  "Ravencliff": "Liverpoul",
  "Elmshire": "Monchester City",
  "Highgate": "Monchester United",
  "Marston Vale": "Newcastle City",
  "Kingsley": "Nottingham Wood",
  "Sandborough": "Sunderland Town",
  "Oakhaven": "Tottenham Hotspurs",

  // 2026/27 Championship inspired set — all 24 clubs.
  "Ridgeport": "Birmingham United",
  "Thornbury": "Blackburn Town",
  "Larkfield United": "Bolton Wanderers",
  "Castleford Rovers": "Bristol United",
  "Penhale": "Burnley Town",
  "Wexbridge": "Cardiff Town",
  "Ironvale": "Charlton United",
  "Merrow Athletic": "Derby City",
  "Draymoor": "Lincoln Town",
  "Colverton": "Middlesborough",
  "Ashby Rangers": "Millwall Town",
  "Sea View United": "Norwich United",
  "Nortonwood": "Portsmouth City",
  "Beckwith": "Preston North",
  "Hollowfield": "Queens Park United",
  "Grangemouth City": "Sheffield City",
  "Verity Park": "Southampton City",
  "Stonebridge": "Stoke Town",
  "Tarnbeck": "Swansea Town",
  "Duncastle": "Watford City",
  "Little Marsh FC": "West Bromwich City",
  "Ferrisdale": "Westham United",
  "Oldcourt Wanderers": "Wolverton Wanderers",
  "Alderwick Town": "Wrexhum AFC",

  // 2026/27 League One inspired set — all 24 clubs.
  "Brambleford": "AFC Wimbeldon",
  "Creston Athletic": "Barnsley City",
  "Dunmere United": "Blackpool City",
  "Eastborough": "Bradford United",
  "Foxley Rovers": "Bromley City",
  "Glenhaven": "Burton City",
  "Hartwick City": "Cambridge City",
  "Ivydale": "Doncaster Town",
  "Juniper Town": "Huddersfield City",
  "Kirkstead": "Leicestor City",
  "Langford Athletic": "Leyton Orion",
  "Moorhaven": "Luton City",
  "Norchester": "Mansfield City",
  "Oakmere United": "MK United",
  "Pemberton Rovers": "Notts City",
  "Queensferry Athletic": "Oxford City",
  "Redmarsh": "Peterborough City",
  "Stonely Town": "Plymouth United",
  "Westcombe": "Reading City",
  "Arden Vale": "Sheffield Wednsday",
  "Briarley": "Stevenage City",
  "Coldwater City": "Stockport City",
  "Dalesford United": "Wigan United",
  "Evermoor": "Wycombe United",

  // 2026/27 League Two inspired set — all 24 clubs.
  "Farnwick Athletic": "Accrington City",
  "Greycastle": "Barnet United",
  "Hawthorne Rovers": "Bristol Rovers",
  "Inglemere": "Cheltenham City",
  "Kingswell Town": "Chesterfield City",
  "Lowfield United": "Colchester City",
  "Mereford": "Crawley City",
  "Northcross Athletic": "Crewe Alexanders",
  "Orchard Vale": "Exeter City",
  "Parkminster": "Fleetwood City",
  "Ravenswood City": "Gillingham City",
  "Southmere": "Grimsby City",
  "Telford Vale": "Newport City",
  "Underhill Rovers": "Northampton City",
  "Westhaven Athletic": "Oldham City",
  "Banbury Cross": "Port Vale City",
  "Brackley Borough": "Rochdale Town",
  "Kettering Athletic": "Rotherham City",
  "Stourbridge Town": "Salford United",
  "Redditch Borough": "Shrewsbury City",
  "Stratford Athletic": "Swindon City",
  "Halesowen FC": "Tranmere United",
  "Bedford Borough": "Walsall City",
  "Stamford Town": "York United",

  // Lower-pyramid presentation aliases. These start after the four EFL blocks,
  // so expanding divisions cannot silently push an EFL analogue into the wrong league.
  "Spalding Athletic": "Spalding City",
  "Leamington Vale": "Leamington City",
  "Nuneaton Borough": "Nuneaton City",
  "Bromsgrove Athletic": "Bromsgrove Sport",
  "Coalville Town": "Coalville United",
  "Harborough United": "Harborough City",
  "Royston Borough": "Royston City",
  "Hitchin Athletic": "Hitchin City",

  // Level 7 South
  "Barwell Town": "Barwell United",
  "Alvechurch FC": "Alvechurch Town",
  "Needham Borough": "Needham Market Town",
  "Salisbury Rovers": "Salisbury City",
  "Poole Athletic": "Poole City",
  "Dorchester Town": "Dorchester City",
  "Wimborne United": "Wimborne City",
  "Taunton Borough": "Taunton City",
  "Tiverton Athletic": "Tiverton City",
  "Plymouth Parkway": "Plymouth Parkways",
  "Gosport Town": "Gosport United",
  "Havant Borough": "Havant & Waterloovale",
  "Walton Athletic": "Walton & Hersham United",
  "Bracknell Town": "Bracknell City",
  "Chertsey Rovers": "Chertsey City",
  "Hungerford United": "Hungerford City",
  "Swindon Borough": "Swindon Supermarines",
  "Gloucester Vale": "Gloucester United",
  "Basingstoke Town": "Basingstoke City",
  "Sholing Athletic": "Sholing United",

  // Level 7 Isthmian
  "Winchester City": "Winchester United",
  "Farnborough Rovers": "Farnborough United",
  "Weston Athletic": "Weston-super-Mare City",
  "Hornchurch Athletic": "Hornchurch United",
  "Dulwich Borough": "Dulwich Hamlets",
  "Lewes Town": "Lewes United",
  "Folkestone United": "Folkestone Invicto",
  "Cray Wanderers": "Cray United",
  "Billericay Town": "Billericay City",
  "Chatham Athletic": "Chatham City",
  "Horsham Borough": "Horsham United",
  "Carshalton United": "Carshalton Athletico",
  "Hashtag Athletic": "Hashtag City",
  "Potters Bar Town": "Potters Bar City",
  "Wingate Borough": "Wingate & Finchly",
  "Canvey Athletic": "Canvey Isles",
  "Whitehawk FC": "Whitehawks",
  "Bognor Regis Town": "Bognor Regis City",
  "Hendon Borough": "Hendon United",
  "Cheshunt Athletic": "Cheshunt United",

  // Level 7 North
  "Dartford Rovers": "Dartford United",
  "Ramsgate Town": "Ramsgate United",
  "Burgess Hill Athletic": "Burgess Hill City",
  "Macclesfield Town": "Macclesfield United",
  "Worksop Athletic": "Worksop City",
  "Hyde United": "Hyde City",
  "Morpeth Town": "Morpeth City",
  "Whitby Athletic": "Whitby City",
  "Ashton Borough": "Ashton City",
  "Guiseley Town": "Guiseley United",
  "Lancaster City": "Lancaster United",
  "Prescot Rovers": "Prescot Cablers",
  "Ilkeston Athletic": "Ilkeston City",
  "Matlock Town": "Matlock City",
  "Bamber Bridge FC": "Bamber Bridges",
  "Hebburn Athletic": "Hebburn City",
  "Mickleover Town": "Mickleover United",
  "Gainsborough Athletic": "Gainsborough Trinty",
  "Workington Borough": "Workington United",
  "Warrington Town": "Warrington City",
  "Stockton Athletic": "Stockton City",
  "Leek Town": "Leek City",
  "Basford United": "Basford City",
};

export function clubPresentationName(sourceName: string): string {
  return CLUB_PRESENTATION_ALIASES[sourceName] ?? sourceName;
}

/**
 * Competition labels are also presentation-only. IDs and persisted league
 * names remain stable underneath so old saves do not need a migration.
 */
const LEAGUE_PRESENTATION_ALIASES: Record<string, string> = {
  "Division One": "Premier Division",
  "Division Two": "Championship",
  "Division Three": "League One",
  "Division Four": "League Two",
  "Regional Premier Central": "Southern Premier Central",
  "Regional Premier South": "Southern Premier South",
  "Regional Premier Isthmian": "Isthmian Premier",
  "Regional Premier North": "Northern Premier",
};

export function leaguePresentationName(sourceName: string): string {
  return LEAGUE_PRESENTATION_ALIASES[sourceName] ?? sourceName;
}
