/* =========================================================================
   Club name pool for the football pyramid.
   -------------------------------------------------------------------------
   Eight divisions of 20 clubs = 160 persistent world slots once the first
   four Level 7 regional divisions are enabled. The user's club takes one of
   them, so 159+ AI names are required.

   IMPORTANT: order is save-sensitive. Existing names retain their historical
   order; world-expansion names are append-only so older save composition is
   deterministic and future migrations have a stable source pool.
========================================================================= */

export const CLUBS: string[] = [
  // Historic tier-1 core (unchanged order — pre-v4 saves depend on it)
  "Dalton Town",
  "Ashford City",
  "Millbrook",
  "Northfield",
  "Redwood FC",
  "Kingsbridge",
  "Halewood United",
  "Stanmoor",
  "Fairwind",
  "Portlee",
  "Blackrock Athletic",
  "Silverdale",
  "Whitby Rangers",
  "Broadmarsh",
  "Ravencliff",
  "Elmshire",
  "Highgate",
  "Marston Vale",
  "Kingsley",
  "Sandborough",
  "Oakhaven",
  "Ridgeport",
  // Original second-tier expansion
  "Thornbury",
  "Larkfield United",
  "Castleford Rovers",
  "Penhale",
  "Wexbridge",
  "Ironvale",
  "Merrow Athletic",
  "Draymoor",
  "Colverton",
  "Ashby Rangers",
  "Sea View United",
  "Nortonwood",
  "Beckwith",
  "Hollowfield",
  "Grangemouth City",
  "Verity Park",
  "Stonebridge",
  "Tarnbeck",
  "Duncastle",
  "Little Marsh FC",
  "Ferrisdale",
  "Oldcourt Wanderers",
  // Persistent outer-world expansion. Append only.
  "Alderwick Town",
  "Brambleford",
  "Creston Athletic",
  "Dunmere United",
  "Eastborough",
  "Foxley Rovers",
  "Glenhaven",
  "Hartwick City",
  "Ivydale",
  "Juniper Town",
  "Kirkstead",
  "Langford Athletic",
  "Moorhaven",
  "Norchester",
  "Oakmere United",
  "Pemberton Rovers",
  "Queensferry Athletic",
  "Redmarsh",
  "Stonely Town",
  "Westcombe",
  "Arden Vale",
  "Briarley",
  "Coldwater City",
  "Dalesford United",
  "Evermoor",
  "Farnwick Athletic",
  "Greycastle",
  "Hawthorne Rovers",
  "Inglemere",
  "Kingswell Town",
  "Lowfield United",
  "Mereford",
  "Northcross Athletic",
  "Orchard Vale",
  "Parkminster",
  "Ravenswood City",
  "Southmere",
  "Telford Vale",
  "Underhill Rovers",
  "Westhaven Athletic",

  // Level 7 regional expansion. Append only: never reorder above this line.
  "Banbury Cross",
  "Brackley Borough",
  "Kettering Athletic",
  "Stourbridge Town",
  "Redditch Borough",
  "Stratford Athletic",
  "Halesowen FC",
  "Bedford Borough",
  "Stamford Town",
  "Spalding Athletic",
  "Leamington Vale",
  "Nuneaton Borough",
  "Bromsgrove Athletic",
  "Coalville Town",
  "Harborough United",
  "Royston Borough",
  "Hitchin Athletic",
  "Barwell Town",
  "Alvechurch FC",
  "Needham Borough",

  "Salisbury Rovers",
  "Poole Athletic",
  "Dorchester Town",
  "Wimborne United",
  "Taunton Borough",
  "Tiverton Athletic",
  "Plymouth Parkway",
  "Gosport Town",
  "Havant Borough",
  "Walton Athletic",
  "Bracknell Town",
  "Chertsey Rovers",
  "Hungerford United",
  "Swindon Borough",
  "Gloucester Vale",
  "Basingstoke Town",
  "Sholing Athletic",
  "Winchester City",
  "Farnborough Rovers",
  "Weston Athletic",

  "Hornchurch Athletic",
  "Dulwich Borough",
  "Lewes Town",
  "Folkestone United",
  "Cray Wanderers",
  "Billericay Town",
  "Chatham Athletic",
  "Horsham Borough",
  "Carshalton United",
  "Hashtag Athletic",
  "Potters Bar Town",
  "Wingate Borough",
  "Canvey Athletic",
  "Whitehawk FC",
  "Bognor Regis Town",
  "Hendon Borough",
  "Cheshunt Athletic",
  "Dartford Rovers",
  "Ramsgate Town",
  "Burgess Hill Athletic",

  "Macclesfield Town",
  "Worksop Athletic",
  "Hyde United",
  "Morpeth Town",
  "Whitby Athletic",
  "Ashton Borough",
  "Guiseley Town",
  "Lancaster City",
  "Prescot Rovers",
  "Ilkeston Athletic",
  "Matlock Town",
  "Bamber Bridge FC",
  "Hebburn Athletic",
  "Mickleover Town",
  "Gainsborough Athletic",
  "Workington Borough",
  "Warrington Town",
  "Stockton Athletic",
  "Leek Town",
  "Basford United",
];
