/* Determinism lock — the Phase 0 safety net.
   Run with:  bun src/lib/game/__checks__/snapshot.check.ts
   Refresh baselines with: bun src/lib/game/__checks__/snapshot.check.ts --write

   A fixed-seed run of the simulation must produce a bit-identical gameplay state
   before and after any structural refactor. Persisted schema metadata is normalized
   to the frozen baseline schema so an intentional version bump cannot masquerade as
   gameplay drift.
*/
import { newGame, advanceWeek } from "../engine";
import { stateHash, stateHashParts } from "../diagnostics/stateHash";
import { BASELINE } from "./snapshot.baseline";
import type { GameState } from "../types";

let passed = 0;
let failed = 0;
function check(label: string, cond: boolean, extra?: string) {
  if (cond) {
    passed++;
    console.log(`  ✓ ${label}`);
  } else {
    failed++;
    console.log(`  ✗ ${label}${extra ? " — " + extra : ""}`);
  }
}

const SEED = "PHASE0|SNAPSHOT|FIXED";
const WEEKS_PER_SEASON = 46;
// The recorded fingerprints were taken at schema v12. Keep this frozen: the
// snapshot protects simulation behaviour, while migration suites protect schema.
const SNAPSHOT_SCHEMA_BASELINE = 12;

type SnapshotState = Omit<GameState, "version"> & { version: number };

function run(weeks: number): GameState {
  let s = newGame("Snapshot Town", "A. Baseline", SEED);
  for (let i = 0; i < weeks; i++) s = advanceWeek(s);
  return s;
}

function gameplayState(state: GameState): SnapshotState {
  return { ...structuredClone(state), version: SNAPSHOT_SCHEMA_BASELINE };
}

function gameplayHash(state: GameState): string {
  return stateHash(gameplayState(state) as GameState);
}

function gameplayHashParts(state: GameState): Record<string, string> {
  const parts = stateHashParts(gameplayState(state) as GameState);
  delete parts.version;
  return parts;
}

const points: { label: string; weeks: number }[] = [
  { label: "season1-week10", weeks: 10 },
  { label: "season1-end", weeks: WEEKS_PER_SEASON },
  { label: "season3-end", weeks: WEEKS_PER_SEASON * 3 },
];

const write = process.argv.includes("--write");
const results: Record<string, string> = {};

console.log("\n[S1] Deterministic simulation fingerprints");
for (const p of points) {
  const s = run(p.weeks);
  const h = gameplayHash(s);
  results[p.label] = h;
  if (write) {
    console.log(`  · ${p.label} = ${h}`);
  } else {
    const expected = BASELINE[p.label];
    check(`${p.label} gameplay hash unchanged (${h})`, expected === h, `expected ${expected}`);
    if (expected !== h) {
      const parts = gameplayHashParts(s);
      const basisParts = BASELINE.parts?.[p.label];
      if (basisParts) {
        const drift = Object.keys(parts).filter((k) => parts[k] !== basisParts[k]);
        console.log(`     drifted keys: ${drift.join(", ") || "(structure changed)"}`);
      }
    }
  }
}

console.log("\n[S2] Same seed twice is identical");
check(
  "two independent runs agree",
  gameplayHash(run(WEEKS_PER_SEASON)) === gameplayHash(run(WEEKS_PER_SEASON)),
);

console.log("\n[S3] Different seeds diverge");
{
  let a = newGame("Snapshot Town", "A. Baseline", "SEED-A");
  let b = newGame("Snapshot Town", "A. Baseline", "SEED-B");
  for (let i = 0; i < 20; i++) {
    a = advanceWeek(a);
    b = advanceWeek(b);
  }
  check("seed changes the world", gameplayHash(a) !== gameplayHash(b));
}

if (write) {
  const parts: Record<string, Record<string, string>> = {};
  for (const p of points) parts[p.label] = gameplayHashParts(run(p.weeks));
  const body =
    `/* AUTO-GENERATED by snapshot.check.ts --write. Do not hand-edit.\n` +
    `   These fingerprints lock gameplay behaviour; schema metadata is normalized. */\n` +
    `export const BASELINE: Record<string, string> & { parts?: Record<string, Record<string, string>> } = ${JSON.stringify(
      { ...results, parts },
      null,
      2,
    )} as never;\n`;
  const { writeFileSync } = await import("node:fs");
  const { fileURLToPath } = await import("node:url");
  writeFileSync(fileURLToPath(new URL("./snapshot.baseline.ts", import.meta.url)), body);
  console.log("\nBaseline written.");
} else {
  console.log(`\n${passed} passed, ${failed} failed`);
  if (failed) process.exit(1);
}
